package com.pkg.beans;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Item.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Item implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Item_ID. */
	private Integer itemId;

	/** Item_Name. */
	private String itemName;

	/** Item_Model. */
	private String itemModel;

	/** Item_Color. */
	private String itemColor;

	/** Item_Price. */
	private double itemPrice;

	/** Item_Category. */
	private String itemCategory;

	
	/**
	 * Set the Item_ID.
	 * 
	 * @param itemId
	 *            Item_ID
	 */
	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	/**
	 * Get the Item_ID.
	 * 
	 * @return Item_ID
	 */
	public Integer getItemId() {
		return this.itemId;
	}

	/**
	 * Set the Item_Name.
	 * 
	 * @param itemName
	 *            Item_Name
	 */
	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	/**
	 * Get the Item_Name.
	 * 
	 * @return Item_Name
	 */
	public String getItemName() {
		return this.itemName;
	}

	/**
	 * Set the Item_Model.
	 * 
	 * @param itemModel
	 *            Item_Model
	 */
	public void setItemModel(String itemModel) {
		this.itemModel = itemModel;
	}

	/**
	 * Get the Item_Model.
	 * 
	 * @return Item_Model
	 */
	public String getItemModel() {
		return this.itemModel;
	}

	/**
	 * Set the Item_Color.
	 * 
	 * @param itemColor
	 *            Item_Color
	 */
	public void setItemColor(String itemColor) {
		this.itemColor = itemColor;
	}

	/**
	 * Get the Item_Color.
	 * 
	 * @return Item_Color
	 */
	public String getItemColor() {
		return this.itemColor;
	}

	/**
	 * Set the Item_Price.
	 * 
	 * @param d
	 *            Item_Price
	 */
	public void setItemPrice(double d) {
		this.itemPrice = d;
	}

	/**
	 * Get the Item_Price.
	 * 
	 * @return Item_Price
	 */
	public double getItemPrice() {
		return this.itemPrice;
	}

	/**
	 * Set the Item_Category.
	 * 
	 * @param itemCategory
	 *            Item_Category
	 */
	public void setItemCategory(String itemCategory) {
		this.itemCategory = itemCategory;
	}

	/**
	 * Get the Item_Category.
	 * 
	 * @return Item_Category
	 */
	public String getItemCategory() {
		return this.itemCategory;
	}

	/**
	 * Set the set of the ItemStore.
	 * 
	 * @param itemstoreSet
	 *            The set of ItemStore
	 */


	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((itemId == null) ? 0 : itemId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Item other = (Item) obj;
		if (itemId == null) {
			if (other.itemId != null) {
				return false;
			}
		} else if (!itemId.equals(other.itemId)) {
			return false;
		}
		return true;
	}

}
